import random

ben10_data = {
"aliens": [
  {"id": 0, "name": "Alien X", "powers": "Reality Warping, Omniscience, Omnipotence", "homeplanet": "The Forge of Creation", "species": "Celestialsapien", "description": "Alien X is an extremely powerful and complex alien with reality-warping abilities, omniscience, and omnipotence. He comes from the Forge of Creation, the birthplace of the Celestialsapiens.", "weakness": "Requires a unanimous decision from all three personalities to take any action. Disagreements can lead to inaction.", "appearance": "A humanoid alien with three faces representing different personalities and floating in a cosmic background."},
  {"id": 1, "name": "Heatblast", "powers": "Pyrokinesis, Heat Immunity", "homeplanet": "Pyros", "species": "Pyronite", "description": "Heatblast is a fiery alien with the ability to generate intense heat and fire. He hails from the volcanic planet Pyros.", "weakness": "Water can temporarily extinguish his flames.", "appearance": "A humanoid made of molten lava."},
  {"id": 2, "name": "Stinkfly", "powers": "Flight, Acidic Slime Projection", "homeplanet": "Lepidopterra", "species": "Lepidopterran", "description": "Stinkfly is a flying insectoid alien capable of shooting corrosive slime. He comes from the swampy planet Lepidopterra.", "weakness": "Sensitive to strong smells, which can impair his vision.", "appearance": "Resembles a giant insect with wings."},
  {"id": 3, "name": "Four Arms", "powers": "Enhanced Strength, Quadruple Limbs", "homeplanet": "Khoros", "species": "Tetramand", "description": "Four Arms is a powerful, four-armed alien known for his incredible strength. He originates from the militaristic planet Khoros.", "weakness": "Can be slowed down by his own bulkiness.", "appearance": "A large, muscular humanoid with four arms."},
  {"id": 4, "name": "Diamondhead", "powers": "Crystallokinesis, Diamond Constructs", "homeplanet": "Petropia", "species": "Petrosapien", "description": "Diamondhead can manipulate and create diamond-like structures. He hails from the shattered planet Petropia.", "weakness": "Vulnerable to sonic vibrations that can shatter his crystals.", "appearance": "A crystalline alien with sharp facets."},
  {"id": 5, "name": "XLR8", "powers": "Super Speed, Enhanced Reflexes", "homeplanet": "Kinet", "species": "Kineceleran", "description": "XLR8 is a speedster alien with the ability to move at incredible velocities. He comes from the fast-paced planet Kinet.", "weakness": "Can be tripped up easily due to his high speed.", "appearance": "A blue, humanoid alien with a streamlined design."},
  {"id": 6, "name": "Wildmutt", "powers": "Enhanced Senses, Agility", "homeplanet": "Vulpin", "species": "Vulpimancer", "description": "Wildmutt is a feral, animalistic alien with heightened senses and agility. He originates from the wild and untamed planet Vulpin.", "weakness": "Lack of sight, relies on other senses.", "appearance": "A four-legged, feline-like creature with no visible eyes."},
  {"id": 7, "name": "Ghostfreak", "powers": "Invisibility, Tentacles", "homeplanet": "Anur Phaetos", "species": "Ectonurite", "description": "Ghostfreak is a ghost-like alien with the ability to turn invisible and extend tentacles. He comes from the eerie planet Anur Phaetos.", "weakness": "Vulnerable to sunlight, which can weaken and harm him.", "appearance": "A floating, ghostly figure with tentacles."},
  {"id": 8, "name": "Ripjaws", "powers": "Underwater Breathing, Enhanced Strength", "homeplanet": "Piscciss", "species": "Piscciss Volann", "description": "Ripjaws is an aquatic alien with the ability to breathe underwater and possess enhanced strength. He hails from the oceanic planet Piscciss.", "weakness": "Dependent on water for survival.", "appearance": "A fish-like humanoid with sharp teeth."},
  {"id": 9, "name": "Upgrade", "powers": "Technological Integration, Shape-shifting", "homeplanet": "Galvan B", "species": "Galvanic Mechamorph", "description": "Upgrade is a living, technological entity that can merge with and enhance machinery. He originates from the advanced planet Galvan B.", "weakness": "Vulnerable when not integrated with technology.", "appearance": "A metallic, liquid-like being with circuit patterns."},
  {"id": 10, "name": "Grey Matter", "powers": "Intellectual Genius, Size Manipulation", "homeplanet": "Galvan Prime", "species": "Galvan", "description": "Grey Matter is a small-sized alien with exceptional intelligence and the ability to manipulate his own size. He comes from the brainy planet Galvan Prime.", "weakness": "Physically weak and vulnerable due to his small size.", "appearance": "A tiny, humanoid alien with a large brain."},
  {"id": 11, "name": "Wildvine", "powers": "Plant Manipulation, Regeneration", "homeplanet": "Flors Verdance", "species": "Florauna", "description": "Wildvine is a plant-based alien with the ability to control plant life and regenerate. He originates from the lush planet Flors Verdance.", "weakness": "Fire can be particularly effective against him.", "appearance": "A humanoid made of vines and plant matter."},
  {"id": 12, "name": "Perk Upchuck", "powers": "Digestive Assimilation, Energy Projection", "homeplanet": "Peptos XI", "species": "Perk Gourmand", "description": "Perk Upchuck can eat and digest almost anything, gaining special abilities. He comes from the digestive-centric planet Peptos XI.", "weakness": "Overeating can lead to uncontrollable transformations.", "appearance": "A small, round creature with multiple eyes and a large mouth."},
  {"id": 13, "name": "Articguana", "powers": "Cryokinesis, Ice Breath", "homeplanet": "X'Nelli", "species": "Polar Manzardill", "description": "Articguana is an icy alien with the ability to generate and control ice. He hails from the frozen planet X'Nelli.", "weakness": "Extreme heat can weaken his ice-based powers.", "appearance": "A humanoid with a reptilian appearance, covered in ice."},
  {"id": 14, "name": "Buzzshock", "powers": "Electrokinesis, Electrical Flight", "homeplanet": "Nosedeen Quasar", "species": "Nosedeenian", "description": "Buzzshock is an electric alien capable of generating and controlling electricity. He comes from the energy-focused planet Nosedeen Quasar.", "weakness": "Water can short-circuit his electrical abilities.", "appearance": "A small, electrically-charged being."},
  {"id": 15, "name": "Snare-oh", "powers": "Bandage Manipulation, Enhanced Agility", "homeplanet": "Anur Khufos", "species": "Thep Khufan", "description": "Snare-oh has the ability to control and manipulate bandages, as well as possess enhanced agility. He originates from the eerie planet Anur Khufos.", "weakness": "Vulnerable to strong winds that can unravel his bandages.", "appearance": "A mummy-like alien with bandages covering his body."},
  {"id": 16, "name": "Frankenstrike", "powers": "Electrokinesis, Enhanced Strength", "homeplanet": "Anodyne", "species": "Transylian", "description": "Frankenstrike is a powerful electric alien with enhanced strength. He comes from the high-tech planet Anodyne.", "weakness": "Water can conduct and affect his electrical powers.", "appearance": "A large, humanoid creature with electrical arcs."},
  {"id": 17, "name": "Upchuck", "powers": "Energy Ingestion, Energy Projection", "homeplanet": "Peptos XI", "species": "Perk Gourmand", "description": "Upchuck can eat and redirect energy projectiles. He originates from the digestive-centric planet Peptos XI.", "weakness": "Overeating can lead to uncontrollable transformations.", "appearance": "A small, round creature with multiple eyes and a large mouth."},
  {"id": 18, "name": "Ditto", "powers": "Self-Duplication", "homeplanet": "Kinet", "species": "Splixson", "description": "Ditto has the ability to create duplicates of himself. He comes from the fast-paced planet Kinet.", "weakness": "Each duplicate shares the same consciousness, so harm to one affects all.", "appearance": "A small, humanoid alien with a simplistic design."},
  {"id": 19, "name": "Eye Guy", "powers": "Optic Beams, 360-Degree Vision", "homeplanet": "Sightra", "species": "Opticoid", "description": "Eye Guy has multiple eyes and can shoot optic beams. He originates from the planet Sightra.", "weakness": "Bright lights can temporarily blind his numerous eyes.", "appearance": "A multi-eyed creature with various eye types."},
  {"id": 20, "name": "Way Big", "powers": "Gigantism, Cosmic Rays", "homeplanet": "Cosmic Storms", "species": "To'kustar", "description": "Way Big is a colossal alien with the ability to grow to immense sizes and shoot cosmic rays. He comes from the turbulent cosmic storms.", "weakness": "Slow and less agile due to his enormous size.", "appearance": "A giant humanoid with cosmic energy emanating from his body."},
  {"id": 21, "name": "Swampfire", "powers": "Chlorokinesis, Pyro Immunity", "homeplanet": "Methanos", "species": "Methanosian", "description": "Swampfire is a plant-based alien with the ability to control plants and immunity to fire. He hails from the swampy planet Methanos.", "weakness": "Extreme heat can temporarily weaken his plant-based abilities.", "appearance": "A humanoid made of plant matter with green flames."},
  {"id": 22, "name": "Chromastone", "powers": "Energy Absorption, Energy Projection", "homeplanet": "Crystalsapien", "species": "Crystalsapien", "description": "Chromastone can absorb and manipulate energy. He originates from the crystalline planet Crystalsapien.", "weakness": "Sound waves can destabilize his crystal structure.", "appearance": "A crystalline alien with a prismatic appearance."},
  {"id": 23, "name": "Big Chill", "powers": "Intangibility, Ice Breath", "homeplanet": "Kylmyys", "species": "Necrofriggian", "description": "Big Chill is an ice-based alien with the ability to turn intangible and breathe ice. He comes from the icy planet Kylmyys.", "weakness": "Fire can temporarily negate his ice powers.", "appearance": "A humanoid with insectoid wings and a ghostly appearance."},
  {"id": 24, "name": "Goop", "powers": "Malleability, Acidic Slime", "homeplanet": "Viscosia", "species": "Polymorph", "description": "Goop is a gooey, malleable alien with acidic slime capabilities. He originates from the chemical-rich planet Viscosia.", "weakness": "Vulnerable when separated into smaller gooey parts.", "appearance": "A green, slimy creature with a simple humanoid shape."},
  {"id": 25, "name": "Echo Echo", "powers": "Sonic Screams, Sonic Duplication", "homeplanet": "Sonorosia", "species": "Sonorosian", "description": "Echo Echo can emit powerful sonic screams and duplicate himself. He hails from the sonic-based planet Sonorosia.", "weakness": "Sonic disruptions can disrupt his sonic abilities.", "appearance": "A small, blue, humanoid alien with soundwave patterns."},
  {"id": 26, "name": "Brainstorm", "powers": "Electrokinesis, Enhanced Intelligence", "homeplanet": "Teslavorr", "species": "Cerebrocrustacean", "description": "Brainstorm is a highly intelligent alien with electrokinetic abilities. He comes from the technologically advanced planet Teslavorr.", "weakness": "Vulnerable to physical attacks due to his small size.", "appearance": "A crab-like alien with a large brain."},
  {"id": 27, "name": "Spidermonkey", "powers": "Enhanced Agility, Web Generation", "homeplanet": "Aranhaschimmia", "species": "Arachnichimp", "description": "Spidermonkey is a monkey-like alien with enhanced agility and the ability to generate webs. He originates from the jungle planet Aranhaschimmia.", "weakness": "Fire can burn through his webs and affect him.", "appearance": "A monkey-like creature with spider-like features."},
  {"id": 28, "name": "Lodestar", "powers": "Magnetism Manipulation, Flight", "homeplanet": "Hauptstadt", "species": "Biosovortian", "description": "Lodestar can manipulate magnetism and fly. He comes from the magnetic planet Hauptstadt.", "weakness": "Powerful magnetic fields can disrupt his abilities.", "appearance": "A metallic, humanoid alien with magnetic properties."},
  {"id": 29, "name": "Rath", "powers": "Enhanced Strength, Aggression Empowerment", "homeplanet": "Appoplexia", "species": "Appoplexian", "description": "Rath is a fierce, cat-like alien with enhanced strength and the ability to get stronger when angry. He hails from the aggressive planet Appoplexia.", "weakness": "His aggressive nature can sometimes cloud his judgment.", "appearance": "A muscular, tiger-like alien with a mane."},
  {"id": 30, "name": "Nanomech", "powers": "Size Manipulation, Flight", "homeplanet": "Galvan Prime", "species": "Galvanic Mechamorph", "description": "Nanomech is a small-sized alien with the ability to manipulate his size and fly. He comes from the brainy planet Galvan Prime.", "weakness": "Physically weak due to his small size.", "appearance": "A tiny, insect-like alien with metallic components."},
  {"id": 31, "name": "Water Hazard", "powers": "Hydrokinesis, Water Projection", "homeplanet": "Orishan", "species": "Orishan", "description": "Water Hazard is a water-based alien with the ability to manipulate and project water. He originates from the aquatic planet Orishan.", "weakness": "Can be dehydrated and weakened when separated from water.", "appearance": "A humanoid alien with water-like features."},
  {"id": 32, "name": "Terraspin", "powers": "Aerokinesis, Flight", "homeplanet": "Aeropela", "species": "Geochelone Aerio", "description": "Terraspin is an aerokinetic alien from Aeropela, capable of manipulating air and flying. Belonging to the Geochelone Aerio species, he can create powerful gusts of wind and retract into a protective shell. Despite his calm demeanor, Terraspin becomes formidable in creating storms or deflecting attacks. Excessive use of his powers may lead to fatigue, requiring recovery time."},
  {"id": 33, "name": "Armodrillo", "powers": "Earth Manipulation, Enhanced Strength", "homeplanet": "Terraexcava", "species": "Talpaedan", "description": "Armodrillo is an earth-based alien with the ability to manipulate and control the ground. He hails from the subterranean planet Terraexcava.", "weakness": "Susceptible to seismic disturbances that can disrupt his control over the earth.", "appearance": "A heavily armored humanoid with earthy features."},
  {"id": 34, "name": "Ampfibian", "powers": "Electrokinesis, Underwater Breathing", "homeplanet": "Piscciss", "species": "Amperi", "description": "AmpFibian is an electric alien with the ability to generate and control electricity. He can also breathe underwater. He comes from the oceanic planet Piscciss.", "weakness": "Vulnerable to insulating materials that can block his electrical abilities.", "appearance": "A sleek, aquatic creature with electrical features."},
  {"id": 35, "name": "NRG", "powers": "Radiation Manipulation, Heat Immunity", "homeplanet": "Nucleria", "species": "Prypiatosian-B", "description": "NRG is a radioactive alien with the ability to manipulate and emit radiation. He originates from the radioactive planet Nucleria.", "weakness": "Susceptible to being contained in specialized suits that block radiation.", "appearance": "A humanoid covered in a protective suit with a glowing core."},
  {"id": 36, "name": "Lodestar", "powers": "Magnetism Manipulation, Flight", "homeplanet": "Hauptstadt", "species": "Biosovortian", "description": "Lodestar can manipulate magnetism and fly. He comes from the magnetic planet Hauptstadt.", "weakness": "Powerful magnetic fields can disrupt his abilities.", "appearance": "A metallic, humanoid alien with magnetic properties."},
  {"id": 37, "name": "Clockwork", "powers": "Chronokinesis, Time Manipulation", "homeplanet": "Chronia", "species": "Chronian", "description": "Clockwork has the ability to manipulate time, slowing down or speeding up events. He comes from the time-manipulating planet Chronia.", "weakness": "Limited physical combat abilities, relies on time manipulation for defense.", "appearance": "A robotic, clock-themed alien."},
  {"id": 38, "name": "Eatle", "powers": "Enhanced Strength, Acidic Saliva", "homeplanet": "Pisciss", "species": "Orishan", "description": "Eatle is a powerful alien with enhanced strength and the ability to generate acidic saliva. He originates from the aquatic planet Pisciss.", "weakness": "Can be temporarily blinded by bright lights.", "appearance": "A large, beetle-like creature with powerful jaws."},
  {"id": 39, "name": "Jury Rigg", "powers": "Technological Intuition, Rapid Invention", "homeplanet": "Revonnah", "species": "Conductoid", "description": "Jury Rigg has an intuitive understanding of technology and can rapidly invent devices on the spot. He comes from the tech-savvy planet Revonnah.", "weakness": "Lack of physical combat abilities, relies on gadgets for defense.", "appearance": "A small, impish alien with a knack for tinkering."},
  {"id": 40, "name": "Feedback", "powers": "Energy Absorption, Energy Projection", "homeplanet": "Terraexcava", "species": "Conductoid", "description": "Feedback can absorb and manipulate various forms of energy. He hails from the subterranean planet Terraexcava.", "weakness": "Overloading with too much energy can be dangerous.", "appearance": "A humanoid alien with electrical features."},
  {"id": 41, "name": "Bloxx", "powers": "Shape-shifting, Block Creation", "homeplanet": "Polyominus", "species": "Segmentasapien", "description": "Bloxx can reshape his body into various forms and create building-block structures. He originates from the geometric planet Polyominus.", "weakness": "Vulnerable when disassembled into individual blocks.", "appearance": "A humanoid alien made up of interlocking blocks."},
  {"id": 42, "name": "Gravattack", "powers": "Gravity Manipulation, Enhanced Durability", "homeplanet": "Keplorr", "species": "Galilean", "description": "Gravattack can control gravity and has enhanced durability. He comes from the dense planet Keplorr.", "weakness": "Struggles against opponents with strong gravitational powers.", "appearance": "A large, rock-like alien with control over gravity."},
  {"id": 43, "name": "Crashhopper", "powers": "Enhanced Jumping, Exoskeleton", "homeplanet": "Lepidopterra", "species": "Orthopterran", "description": "Crashhopper is an insectoid alien with powerful jumping abilities and a durable exoskeleton. He comes from the planet Lepidopterra, known for its diverse insect life.", "weakness": "Large and heavy opponents can be challenging for his jumping maneuvers.", "appearance": "A grasshopper-like creature with a tough exoskeleton."},
  {"id": 44, "name": "Ball Weevil", "powers": "Bio-Ball Generation, Adhesive Spheres", "homeplanet": "Atropha", "species": "Unknown", "description": "Ball Weevil can generate explosive bio-balls and adhesive spheres. His origin is unknown, and he seems to be a unique alien species.", "weakness": "Limited combat abilities without the use of bio-balls.", "appearance": "A small, insectoid alien with the ability to generate explosive bio-balls."},
  {"id": 45, "name": "Walkatrout", "powers": "Underwater Breathing, Fish Physiology", "homeplanet": "Ickthyperambuloid", "species": "Ickthyperambuloid", "description": "Walkatrout is an aquatic alien with the ability to breathe underwater and adapt to fish physiology. He hails from the planet Ickthyperambuloid.", "weakness": "Limited mobility on land, optimal in aquatic environments.", "appearance": "A fish-like alien with the ability to walk on legs."},
  {"id": 46, "name": "Pesky Dust", "powers": "Sleep Inducement, Dream Manipulation", "homeplanet": "Lepidopterra", "species": "Nemuina", "description": "Pesky Dust has the ability to induce sleep and manipulate dreams. He comes from the planet Lepidopterra, known for its diverse insect life.", "weakness": "Physically vulnerable, relies on his sleep-inducing powers for defense.", "appearance": "A small, fairy-like alien with insectoid wings."},
  {"id": 47, "name": "Molestache", "powers": "Enhanced Strength, Mustache Manipulation", "homeplanet": "Nosedeen Quasar", "species": "Unknown", "description": "Molestache possesses enhanced strength and the ability to manipulate his mustache for various purposes. His origin is unknown, and he appears to be a unique alien species.", "weakness": "Limited combat abilities without the use of his mustache.", "appearance": "A humanoid alien with a large and versatile mustache."},
  {"id": 48, "name": "The Worst", "powers": "Probability Alteration, Bad Luck Inducement", "homeplanet": "Perplexahedron", "species": "Unknown", "description": "The Worst can alter probabilities, bringing bad luck to his opponents. His origin is associated with the mysterious Perplexahedron.", "weakness": "Limited in direct combat, relies on manipulating probabilities.", "appearance": "A unique and mysterious alien with a cosmic presence."},
  {"id": 49, "name": "Kickin Hawk", "powers": "Enhanced Strength, Martial Arts Skills", "homeplanet": "Terraexcava", "species": "Unknown", "description": "Kickin Hawk possesses enhanced strength and is skilled in martial arts. His origin is associated with the subterranean planet Terraexcava.", "weakness": "May underestimate opponents due to his confident nature.", "appearance": "A humanoid alien with bird-like features and a martial artist aesthetic."},
  {"id": 50, "name": "Toepick", "powers": "Fear Inducement, Protective Faceplate", "homeplanet": "Unknown", "species": "Unknown", "description": "Toepick has the ability to induce fear in his opponents, and he wears a protective faceplate. His origin and species are unknown, adding to the mystery surrounding this alien.", "weakness": "Limited in direct combat, relies on inducing fear for defense.", "appearance": "A mysterious alien with a protective faceplate that conceals his features."},
  {"id": 51, "name": "Astrodactyl", "powers": "Aerial Combat, Sonic Screech", "homeplanet": "Terradino", "species": "Unknown", "description": "Astrodactyl is a flying alien with the ability to engage in aerial combat and emit powerful sonic screeches. His origin is associated with the rocky planet Terradino.", "weakness": "Vulnerable to opponents with strong aerial and sonic abilities.", "appearance": "A pterosaur-like alien with wings and sharp beak."},
  {"id": 52, "name": "Bullfrag", "powers": "Enhanced Agility, Slime Projection", "homeplanet": "Lepidopterra", "species": "Incursean", "description": "Bullfrag possesses enhanced agility and the ability to project slime. He is a member of the Incursean species from the planet Lepidopterra.", "weakness": "Can be hindered by his slimy projections if not used strategically.", "appearance": "An agile and amphibious alien with frog-like features."},
  {"id": 53, "name": "Whampire", "powers": "Hypnosis, Enhanced Strength", "homeplanet": "Unknown", "species": "Vladat", "description": "Whampire possesses the ability to hypnotize and has enhanced strength. He is a member of the Vladat species, and his origin is associated with an unknown planet.", "weakness": "Vulnerable to sunlight, which weakens and harms him.", "appearance": "A vampire-like alien with bat-like wings and hypnotic abilities."},
  {"id": 54, "name": "Gutrot", "powers": "Chemical Manipulation, Gas Generation", "homeplanet": "Unknown", "species": "Unknown", "description": "Gutrot has the ability to manipulate chemicals and generate various gases. His origin and species remain unknown.", "weakness": "Limited in direct combat, relies on chemical manipulation for defense.", "appearance": "A mysterious alien with a gas mask-like appearance."},
  {"id": 56, "name": "Chamalien", "powers": "Invisibility, Camouflage", "homeplanet": "Unknown", "species": "Unknown", "description": "Chamalien can turn invisible and blend into his surroundings using camouflage. His origin and species remain unknown.", "weakness": "Visible to certain types of tracking technology, limiting the effectiveness of his invisibility.", "appearance": "A chameleon-like alien with the ability to change color."},
  {"id": 58, "name": "Fasttrack", "powers": "Super Speed, Enhanced Reflexes", "homeplanet": "Kinet", "species": "Citrakayah", "description": "Fasttrack is a speedster alien with the ability to move at incredible velocities. He comes from the fast-paced planet Kinet.", "weakness": "Can be tripped up easily due to his high speed.", "appearance": "A blue, humanoid alien with a streamlined design."},
  {"id": 57, "name": "Spitter", "powers": "Corrosive Saliva, Acidic Spit", "homeplanet": "Scalpasc", "species": "Spheroid", "description": "Spitter can produce corrosive saliva and spit acidic substances. He hails from the swampy planet Scalpasc.", "weakness": "Needs to replenish saliva for continued use of acidic spit.", "appearance": "A small, amphibious alien with a distinctive head shape."},
  {"id": 60, "name": "Blitzwolfer", "powers": "Sonic Howls, Enhanced Hearing", "homeplanet": "Loboan", "species": "Loboan", "description": "Blitzwolfer has the ability to emit powerful sonic howls and possesses enhanced hearing. He is a member of the Loboan species from the moon Luna Lobo.", "weakness": "Sensitive to high-pitched sounds that can disrupt his enhanced hearing.", "appearance": "A werewolf-like alien with sonic abilities."},
  {"id": 61, "name": "Jetray", "powers": "Flight, Neuroshock Blasts", "homeplanet": "Aeropela", "species": "Petrosapien", "description": "Jetray is a manta ray-like alien capable of flight and the ability to fire neuroshock blasts. He comes from the shattered planet Petropia.", "weakness": "Sensitive to electrical discharges, which can disrupt his flight.", "appearance": "A sleek, winged alien with a ray-like design."}
    ]
}

def get_random_alien():
    return random.choice(ben10_data['aliens'])

def get_alien_by_name(name):
    for alien in ben10_data['aliens']:
        if alien['name'].lower() == name.lower():
            return alien
    return None